require('@alipay/appx-compiler/lib/sjsEnvInit.js');
require('./config$.js');
require('../../pages/index/index.js');
require('../../pages/discovery/discovery.js');
require('../../pages/notify/notify.js');
require('../../pages/chat/chat.js');
require('../../pages/more/more.js');
require('../../pages/answer/answer.js');
require('../../pages/question/question.js');
