
require('./config$.js?appxworker=1');
require('./importScripts$.js?appxworker=1');
function success() {
require('../..//app.js?appxworker=1');
require('../../pages/component/testTwo/icon/icon.js?appxworker=1');
require('../../pages/component/testTwo/text/text.js?appxworker=1');
require('../../pages/component/testTwo/richtext/richtext.js?appxworker=1');
require('../../pages/component/testTwo/progress/progress.js?appxworker=1');
require('../../pages/component/testTwo/button/button.js?appxworker=1');
require('../../pages/component/testTwo/checkbox/checkbox.js?appxworker=1');
require('../../pages/component/testTwo/form/form.js?appxworker=1');
require('../../pages/component/testTwo/input/input.js?appxworker=1');
require('../../pages/component/testTwo/picker/picker.js?appxworker=1');
require('../../pages/component/testTwo/pickview/pickview.js?appxworker=1');
require('../../pages/component/testTwo/radio/radio.js?appxworker=1');
require('../../pages/component/testTwo/slider/slider.js?appxworker=1');
require('../../pages/component/testTwo/switch/switch.js?appxworker=1');
require('../../pages/component/testTwo/textarea/textarea.js?appxworker=1');
require('../../pages/component/testTwo/map/map.js?appxworker=1');
require('../../pages/component/testTwo/canvas/canvas.js?appxworker=1');
require('../../pages/components/test/view/view.js?appxworker=1');
require('../../pages/components/test/scroll-view/scroll-view.js?appxworker=1');
require('../../pages/components/test/swiper/swiper.js?appxworker=1');
require('../../pages/components/test/movable-view/movable-view.js?appxworker=1');
require('../../pages/components/test/cover-view/cover-view.js?appxworker=1');
require('../../pages/components/test/navigator/navigator.js?appxworker=1');
require('../../pages/components/test/image/image.js?appxworker=1');
require('../../pages/components/test/web-view/web-view.js?appxworker=1');
require('../../pages/index/lifeCycles/index.js?appxworker=1');
require('../../pages/openinterface/index.js?appxworker=1');
require('../../pages/equipment/index.js?appxworker=1');
require('../../pages/component/index.js?appxworker=1');
require('../../pages/components/index.js?appxworker=1');
require('../../pages/index/index.js?appxworker=1');
require('../../pages/manage/manage.js?appxworker=1');
require('../../pages/logs/logs.js?appxworker=1');
}
self.bootstrapApp ? self.bootstrapApp({ success }) : success();
